# Generated by Django 4.2.7 on 2024-10-10 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('upload_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.uploadsession')),
            ],
        ),
        migrations.CreateModel(
            name='QuizTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('invigilator1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invigilator1', to='timetable.faculty')),
                ('invigilator2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invigilator2', to='timetable.faculty')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.subject')),
                ('upload_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.uploadsession')),
            ],
        ),
        migrations.CreateModel(
            name='MainTimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], max_length=3)),
                ('time_slot', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=50)),
                ('batch', models.CharField(max_length=20)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.faculty')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.subject')),
                ('upload_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.uploadsession')),
            ],
        ),
        migrations.AddField(
            model_name='faculty',
            name='upload_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.uploadsession'),
        ),
    ]
